apiVersion: skaffold/v2beta12
kind : Config
build: 
  local:
    push : false
  artifacts :
    - image: jigarshah088/multi-client
      context: client 
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .
    - image: jigarshah088/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: jigarshah088/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./*