apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  #replicas: 3
  selector:
    component: web
  ports:
    - port: 3050
      targetPort: 3000
  # template:
  #   metadata:
  #     labels:
  #       component: web

  #   spec:
  #     containers:
  #       - name: client
  #         image: stephengrider/multi-client
  #         ports:
  #           - containerPort: 3000
      